### ISSUE TITLE
The version of typesafe config used requires jdk 8+

### ISSUE THREAD

**Issue by rathboma** [ruippeixotog/scala-scraper#15]
Scala targets jdk 6+, so relying on jdk8 makes it tough for us to deploy this library (we use 7). Would downgrading the config library be out of the question?

**Comment by ruippeixotog** [comment]
Hi @rathboma! I'm not particularly fond of using outdated dependency versions in dependencies, as they'll be "forced" onto projects that depend on scala-scraper and many people (me included) like to have their dependencies up-to-date in order to gat the latest bug fixes and performance improvements.

The ideal setup would be for me to be able to specify different typesafe config versions for different JRE versions, but I don't think Maven supports that for a single JAR. But on your side you can manually exclude the typesafe config I include here and include your own version using SBT, something like:

```scala
libraryDependencies ++= Seq(
  "net.ruippeixotog"   %% "scala-scraper"  % "0.1.2" exclude("com.typesafe", "config"),
  "com.typesafe"        % "config"         % "1.2.1")
```

Does this solution work for you?

**Comment by rathboma** [comment]
Hey,

Thanks for a quick response!

So I understand your reluctance to use an out of date library, but I think
there are two good reasons to think twice about it:

1. Scala 2.11 targets java 6 and lists java 8 support as experimental. We
deploy a lot of Scala apps and have never seen someone running java 8. If
you had a Scala 2.12 build it would make sense to target java 8 there.

2. Even typesafe uses config 1.2.1 in their own Scala projects like slick,
eg https://github.com/slick/slick/blob/master/project/Build.scala. likely
due to the target of java 6.

Bonus: java 8 isn't available out of the box on cent OS 6 or Ubuntu 14.04,
so it's an extra barrier to setup.

Totally up to you what you do, but hope you think about it!

Matthew

please excuse typos - sent from my phone.

**Comment by rathboma** [comment]
Hey just checking in to see what you think?

**Comment by ruippeixotog** [comment]
Hi @rathboma!

Scala 2.11 officially targets Java 6 and has (evolving) experimental support for Java 8, that's a good argument. In my view it's a pretty conservative statement, as it declares support for parsing Java 8 bytecode since 2.11.1 (launched in May 2014!). Unless you are writing Java 8 source code and compiling it together with your Scala sources, I honestly don't see what more support could a Scala compiler need - in particular, it doesn't need to be compiled with JDK8 to be able to support Java 8 runtimes.

As for the examples of people running in JDK8, I can say the systems in production at the company I work are running Scala 2.11 on JDK8 for more than a year now (we are kind of early birds in this aspect, I'll grant you that :smile:).

Just as Slick possibly keeps compatibility with Java 6 runtimes, Akka went a different way. Akka 2.4, launched in September, dropped support for Java 6 and 7 altogether. It seems they are pretty confident about the stability of both the JDK8 and the Scala compiler in order to make that move.

I'd prefer to keep the master branch of scala-scraper depending on the latest stable versions of the dependencies, as I usually do to have the latest bug fixes and improvements. I hope you understand :)
