### ISSUE TITLE
Cool library. But how do I scrape from sites that load with AJAX?

### ISSUE THREAD

**Issue by OElesin** [ruippeixotog/scala-scraper#6]

**Comment by ruippeixotog** [comment]
Hi @OElesin, thanks for your interest in the library! Currently, sites that load with AJAX do not work with scala-scraper. In fact, scala-scraper does not execute JavaScript in the pages at all, which means that HTML elements dynamically inserted in the DOM cannot be extracted with this library.

The alternative would be to load a webpage using one of the several browser automation Java libraries out there, such as [HtmlUnit](http://htmlunit.sourceforge.net/) or [Selenium](http://docs.seleniumhq.org/), and then loading the DOM to scala-scraper with `browser.parseString` if you want to use the implemented scrapers or the DSL. Alternatively, it may be possible to inspect the AJAX requests the page is doing and doing those requests yourself directly in your application, possibly avoiding HTML scraping at all if those requests return JSON or something more machine-readable.

**Comment by nlhkh** [comment]
I actually went ahead with the suggestion and I realize that I can do much of the scraping work in Selenium. What is a compeling reason you would give for one to use selenium to only render source and hand it over to scraper?

**Comment by ruippeixotog** [comment]
Well, the focus of this library is not so much on being featureful, but on providing an idiomatic Scala approach to scraping using a clear functional approach.

Things like wrapping optional results and validations into `Option` and `Either`-like instances allow you to integrate the scraping code better with your own Scala code. Another example of functional approach is that extractors in this scraper are monads: you can create simple extractors and compose them into bigger and more complex examples using familiar combinators like `map` and `flatMap`. Finally, you get a DSL that I hope makes the scraping code short and declarative.

I guess that if your use case requires a full browser implementation like Selenium and you don't mind having some imperative-styled code in your application, you would be better off using Selenium only. I may consider later abstracting this library from the underlying browser/querying engine and allow users to choose between the more lightweight (and probably faster) Jsoup and the full-fledged Selenium driver, though.

**Comment by OElesin** [comment]
Alright. Thanks all. Great knowledge sharing...

**Comment by tepf** [comment]
> I may consider later abstracting this library from the underlying browser/querying engine and allow users to choose between the more lightweight (and probably faster) Jsoup and the full-fledged Selenium driver, though.

It is later now :-)

I've tried using HTMLUnitBrowser but the only thing I got out of it were exceptions. Therefore I moved on to ui4j which works but is very cumbersome to use due to Java 8. Anyway I'd appreciate it if you would add a real browser, because a lot of websites load their content dynamically. Some even require user interaction e.g. hover/click in order to display relevant information.

**Comment by ruippeixotog** [comment]
It is later now indeed :) The browser/querying engine is already decoupled from the core model and the scraping operations, but I ended up implementing support for HtmlUnit instead of Selenium. I want to implement an alternative browser that connects to a "real" browser, via something like webdriver. I didn't think yet of how to support user interaction, though. 

For now, I have been successful in using `HtmlUnitBrowser` for dynamic webpages. For curiosity, can you give me an example (ideally, a minimal one) where `HtmlUnitBrowser` fails to render pages?

**Comment by tepf** [comment]
Maybe I am using it wrong, but I failed to render the google images websites with all the javascript (not the fallback one with deeply nested tables).
